name: Build Plugin

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  COMMIT_SHORT: $(git rev-parse --short ${{ github.sha }})

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build plugin with Gradle
        run: |
          chmod +x gradlew
          ./gradlew buildPlugin

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

      - name: Create release with commit hash
        run: |
          gh release create "build-$COMMIT_SHORT" \
            ./build/distributions/*.zip \
            --title "Build $COMMIT_SHORT ($(date +'%d.%m.%Y'))" \
            --notes "Automatic build from commit ${{ github.sha }}"

      - name: Show release URL
        run: |
          echo "Release created: https://github.com/${{ github.repository }}/releases/tag/build-$COMMIT_SHORT"